/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batchprosys;

//import com.apple.laf.AquaLookAndFeel;
//import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
//import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author prathibha
 */
public class Login2 extends javax.swing.JFrame {
DBOperations dbops=new DBOperations();
static ImageIcon error = new ImageIcon("/Users/prathibha/Desktop/JAVA/BatchProSys/src/batchprosys/messageIcons/error.png");
static ImageIcon sucess = new ImageIcon("/Users/prathibha/Desktop/JAVA/BatchProSys/src/batchprosys/messageIcons/sucess.png");
static ImageIcon warning = new ImageIcon("/Users/prathibha/Desktop/JAVA/BatchProSys/src/batchprosys/messageIcons/warning.png");
static ImageIcon qmark = new ImageIcon("/Users/prathibha/Desktop/JAVA/BatchProSys/src/batchprosys/messageIcons/qmark.png");
//static ProductionPlanner pplanner = new ProductionPlanner();
    /**
     * Creates new form Login2
     */
    public Login2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ForgotPLabel = new javax.swing.JLabel();
        BPSTextField1 = new javax.swing.JTextField();
        BPSPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        BackgroundLayer1 = new javax.swing.JLabel();
        BackgroundLayer2 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Batch Production System-Variosystems-Login");
        jFrame1.getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 728));
        setSize(new java.awt.Dimension(1024, 728));
        getContentPane().setLayout(null);

        ForgotPLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batchprosys/images/fp_mouse_normal.png"))); // NOI18N
        ForgotPLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ForgotPLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ForgotPLabelMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotPLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotPLabelMouseEntered(evt);
            }
        });
        getContentPane().add(ForgotPLabel);
        ForgotPLabel.setBounds(383, 578, 250, 50);

        BPSTextField1.setBackground(new java.awt.Color(238, 237, 237));
        BPSTextField1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        BPSTextField1.setForeground(new java.awt.Color(102, 102, 102));
        BPSTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BPSTextField1.setBorder(null);
        BPSTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPSTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(BPSTextField1);
        BPSTextField1.setBounds(354, 446, 250, 33);

        BPSPasswordField1.setBackground(new java.awt.Color(237, 237, 237));
        BPSPasswordField1.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        BPSPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        BPSPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BPSPasswordField1.setBorder(null);
        BPSPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BPSPasswordField1FocusGained(evt);
            }
        });
        BPSPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BPSPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BPSPasswordField1KeyReleased(evt);
            }
        });
        getContentPane().add(BPSPasswordField1);
        BPSPasswordField1.setBounds(354, 530, 250, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batchprosys/images/normal_mood.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(611, 132, 92, 500);

        BackgroundLayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batchprosys/images/Login2typearea.png"))); // NOI18N
        getContentPane().add(BackgroundLayer1);
        BackgroundLayer1.setBounds(0, 0, 1024, 728);

        BackgroundLayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batchprosys/images/background_Final2.jpg"))); // NOI18N
        getContentPane().add(BackgroundLayer2);
        BackgroundLayer2.setBounds(0, 0, 1090, 728);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/MOUSE_CLICKED final.png"));
        jLabel1.setIcon(II);

    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        
        ImageIcon II = new ImageIcon(getClass().getResource("/batchprosys/images/normal_mood.png"));
        jLabel1.setIcon(II);
        int Interface = dbops.OpenInterface(BPSTextField1.getText());
        int result = dbops.checkUserAvailability(BPSTextField1.getText());

        dbops.getUserName(BPSTextField1.getText());
        //User user=new User();
        //user.setUsername();
        EmailInfo EI = new EmailInfo();
        int checkU = EI.SerachUserID(BPSTextField1.getText());
        if (checkU == 1) {
            if (result == 1) {
                int Check = dbops.checkUsernamePassword(BPSTextField1.getText(), BPSPasswordField1.getText());
                
                if (Check == 1) {
                    //BatchProSys.currentUser=BPSTextField1.getText();
                    if (Interface == 1) {
                        AdminInterface2 ai = new AdminInterface2();
                        ai.setVisible(true);
                        ai.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                    if (Interface == 2) {
                        BatchProSys.currentUser=BPSTextField1.getText();
                        PManager pman = new PManager();
                        pman.setVisible(true);
                        pman.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                    if (Interface == 3) {
                        //BatchProSys.currentUser=BPSTextField1.getText();
                        ProductionPlanner pplanner = new ProductionPlanner();
                        pplanner.setUserName();
                        //User user =userList.get(BPSTextField1.getText());
                        pplanner.setVisible(true);
                        pplanner.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                    if (Interface == 4) {
                        SectionLeader1 sleader = new SectionLeader1();
                        sleader.setVisible(true);
                        sleader.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }

                } else if (Check == 0) {
                    //JOptionPane.showMessageDialog(this, "Username Password mismatch!");
                    JOptionPane.showMessageDialog(null, "Username Password mismatch!", "Warning", JOptionPane.INFORMATION_MESSAGE, warning);

                    BPSTextField1.setText("");
                    BPSPasswordField1.setText("");
                } else {
                    //JOptionPane.showMessageDialog(this, "Error occured while checking username!");
                    JOptionPane.showMessageDialog(null, "Error occured while checking username!", "Error", JOptionPane.INFORMATION_MESSAGE, error);

                    BPSTextField1.setText("");
                    BPSPasswordField1.setText("");
                }
            } else if (result == 0) {
                //JOptionPane.showMessageDialog(this, "You are not longer a valid user");
                JOptionPane.showMessageDialog(null, "You are not longer a valid user", "Warning", JOptionPane.INFORMATION_MESSAGE, warning);
            } else {
                //JOptionPane.showMessageDialog(this, "Error occured while checking Availability!");
                JOptionPane.showMessageDialog(null, "Error occured while checking Availability!", "Error", JOptionPane.INFORMATION_MESSAGE, error);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect UserID", "Error", JOptionPane.INFORMATION_MESSAGE, error);
        }
        //this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/normal_mood.png"));
        jLabel1.setIcon(II);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/MOUSE_enter.png"));
        jLabel1.setIcon(II);

    }//GEN-LAST:event_jLabel1MouseEntered

    private void BPSTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPSTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPSTextField1ActionPerformed

    private void BPSPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BPSPasswordField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BPSPasswordField1FocusGained

    private void BPSPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BPSPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            ImageIcon II = new ImageIcon(getClass().getResource("/batchprosys/images/MOUSE_CLICKED final.png"));
            jLabel1.setIcon(II);
            int Interface = dbops.OpenInterface(BPSTextField1.getText());
            int result = dbops.checkUserAvailability(BPSTextField1.getText());

            dbops.getUserName(BPSTextField1.getText());
            //User user=new User();
            //user.setUsername();
            EmailInfo EI = new EmailInfo();
            int checkU = EI.SerachUserID(BPSTextField1.getText());
            if (checkU == 1) {
                if (result == 1) {
                    int Check = dbops.checkUsernamePassword(BPSTextField1.getText(), BPSPasswordField1.getText());
                    if (Check == 1) {
                        //BatchProSys.currentUser=BPSTextField1.getText();
                        if (Interface == 1) {
                            AdminInterface2 ai = new AdminInterface2();
                            ai.setVisible(true);
                            ai.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }
                        if (Interface == 2) {
                            BatchProSys.currentUser=BPSTextField1.getText();
                            PManager pman = new PManager();
                            pman.setVisible(true);
                            pman.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }
                        if (Interface == 3) {
                            //BatchProSys.currentUser=BPSTextField1.getText();
                            ProductionPlanner pplanner = new ProductionPlanner();
                            pplanner.setUserName();
                            //User user =userList.get(BPSTextField1.getText());
                            pplanner.setVisible(true);
                            pplanner.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }
                        if (Interface == 4) {
                            SectionLeader1 sleader = new SectionLeader1();
                            sleader.setVisible(true);
                            sleader.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }

                    } else if (Check == 0) {
                    //JOptionPane.showMessageDialog(this, "Username Password mismatch!");
                    JOptionPane.showMessageDialog(null, "Username Password mismatch!", "Warning", JOptionPane.INFORMATION_MESSAGE, warning);

                    BPSTextField1.setText("");
                    BPSPasswordField1.setText("");
                } else {
                    //JOptionPane.showMessageDialog(this, "Error occured while checking username!");
                    JOptionPane.showMessageDialog(null, "Error occured while checking username!", "Error", JOptionPane.INFORMATION_MESSAGE, error);

                    BPSTextField1.setText("");
                    BPSPasswordField1.setText("");
                }
            } else if (result == 0) {
                //JOptionPane.showMessageDialog(this, "You are not longer a valid user");
                JOptionPane.showMessageDialog(null, "You are not longer a valid user", "Warning", JOptionPane.INFORMATION_MESSAGE, warning);
            } else {
                //JOptionPane.showMessageDialog(this, "Error occured while checking Availability!");
                JOptionPane.showMessageDialog(null, "Error occured while checking Availability!", "Error", JOptionPane.INFORMATION_MESSAGE, error);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect UserID", "Error", JOptionPane.INFORMATION_MESSAGE, error);
        }
        }
        
    }//GEN-LAST:event_BPSPasswordField1KeyPressed

    private void BPSPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BPSPasswordField1KeyReleased
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/normal_mood.png"));
        jLabel1.setIcon(II);
    }//GEN-LAST:event_BPSPasswordField1KeyReleased

    private void ForgotPLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPLabelMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/fp_mouse_enter.png"));
        ForgotPLabel.setIcon(II);
    }//GEN-LAST:event_ForgotPLabelMouseEntered

    private void ForgotPLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPLabelMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/fp_mouse_normal.png"));
        ForgotPLabel.setIcon(II);
    }//GEN-LAST:event_ForgotPLabelMouseExited

    private void ForgotPLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPLabelMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/fp_mouse_pressed.png"));
        ForgotPLabel.setIcon(II);
    }//GEN-LAST:event_ForgotPLabelMousePressed

    private void ForgotPLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPLabelMouseReleased
        ImageIcon II=new ImageIcon(getClass().getResource("/batchprosys/images/fp_mouse_enter.png"));
        ForgotPLabel.setIcon(II);
        
        if (!"".equals(BPSTextField1.getText())) {
            //System.out.println("-"+BPSTextField1.getText());

            EmailInfo EI = new EmailInfo();
            String arr[] = EI.getEmailInfo(BPSTextField1.getText());
            int check = EI.SerachUserID(BPSTextField1.getText());
            
            if (check == 1) {
                Email_ForgotPass EF = new Email_ForgotPass(arr[3], arr[1], arr[2], arr[0]);
                JOptionPane.showMessageDialog(this, "Email sent to your Email " + arr[3]);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid User-ID.Please Check.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please Enter UserID");
        }
    }//GEN-LAST:event_ForgotPLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField BPSPasswordField1;
    private javax.swing.JTextField BPSTextField1;
    private javax.swing.JLabel BackgroundLayer1;
    private javax.swing.JLabel BackgroundLayer2;
    private javax.swing.JLabel ForgotPLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
